### ISSUE TITLE
Error response from daemon: No such container:dionaea

### ISSUE THREAD

**Issue by firepro20** [dtag-dev-sec/dionaea#1]
For some reason the dockerised version of dionaea on T-Pot system stops working and when running sudo status.sh gives the following
![untitled](https://cloud.githubusercontent.com/assets/17837413/14204780/dd0ab590-f806-11e5-9a95-45196fff43e8.png)

**Comment by t3chn0m4g3** [comment]
This happened sometimes, will be addressed in T-Pot 16.10, systemd allows for better control over start / stop and thus cleaning up dead containers.

Please run `dcres.sh`.
