### ISSUE TITLE
Master version?

### ISSUE THREAD

**Issue by mkayoh** [dtag-dev-sec/dionaea#5]
I've tried multiple times pulling this repo and building the dockerfile myself, each time it has failed with supervisor producing error messages not being able to start dionaea. However when pulling the image from dockerhub everything seems to work just fine (v.16.10). Is this really the same version hosted here? For example the dist/supervisord.conf seems to be different from the one that you'll find on the image pulled from dockerhub in /etc/supervisor/conf.d/supervisord.conf. For example dionaea configs are stored in /etc/dionaea and not /opt/dionaea/etc.

**Comment by t3chn0m4g3** [comment]
@mkayoh This dionaea version is solely developed for [T-Pot](https://github.com/dtag-dev-sec/tpotce). Did you pull `dtagdevsec/dionaea:latest` or `dtagdevsec/dionaea:latest1610`.
There was lots of activity in the [Dinotools Dionaea Repo](https://github.com/dinotools/dionaea) last week and we do not check daily if building works fine :bowtie:

**Comment by mkayoh** [comment]
Ah my mistake, I was pulling the latest and not 16.10. The 16.10 seems to have a similar issue where the container just hangs and dionaea never starts. So to sum it up master branch from git doesn't and the only thing working is the one year old latest branch in dockerhub.

**Comment by t3chn0m4g3** [comment]
@mkayoh As mentioned, it will only work within T-Pot. Try T-Pot 16.10 and you will see that it just works fine :wink:

**Comment by mkayoh** [comment]
Gotcha, thanks for the fast response!

**Comment by t3chn0m4g3** [comment]
@mkayoh Welcome :smiley:
